POST http://localhost:3001/api/blogs
Content-Type: application/json

{

    "title": "Koiran pesun vaikeudet", "author": "Matti Meikäläinen", "url": "https://myspace.com/mattimeikalainen/peseminenonkivaa", "likes": 25,  "userId": "6687d0ae7f81a358356f0237"

}